# Generated by Django 3.1.5 on 2021-01-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='language',
            field=models.CharField(default='python', max_length=20),
        ),
    ]
